name: mve
description: "A state management concept using the Model, View, Event architecture"
version: 1.0.0
homepage:

environment:
  sdk: '>=3.4.0-91.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
